# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: af411846fc2e81d2635c4f54afe6c510de1f123e3a18a085e77f849958f2409c494ab8bebdbe7efe9cd50fa385e3ec46403fb298955a445e0f26b0ef5e2836e0

test:
  secret_key_base: a6c7a07f4755ec76afcbeb25aa12445f9886ecc72fb10d3ddc9bea999621bd51adaeb48c62b0d3e84163cd8fb16de55238fadba4419257c8021a92ebbde92d94

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
